name: 'airflow_learn'

profile: 'airflow_learn'
vars:
  "dbt_ml:audit_schema": "audit"
  "dbt_ml:audit_table": "ml_models"
  ml_enabled: true
  stores: "1, 2, 3, 4"
  depts: "1, 2"
  test_date: "2012-01-01"

on-run-start:
  - '{% do adapter.create_schema(api.Relation.create(target.project, "audit")) %}'
  - "{{ dbt_ml.create_model_audit_table() }}"

models:
  airflow_learn:
    +materialized: view
    churn_analysis:
      +tags: ['churn_analysis']
      +dataset: churn_analysis
    sales_forecast:
      +tags: ['sales_forecast']
      +dataset: sales_forecast
